-- 코드를 입력하세요
-- 2022년 1월의 도서 판매 데이터를 기준으로
-- 저자 별, 카테고리 별 매출액을 구하여
-- 저자 ID, 저자명, 카테고리, 매출액 리스트를 출력
-- 저자 ID 오름차순, 카테고리 내림차순

SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK AS A
INNER JOIN AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES AS C
ON A.BOOK_ID = C.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC;