-- 코드를 입력하세요
-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계 
-- 년, 월, 성별 기준으로 오름차순
-- 성별 정보가 없는 경우 결과에서 제외

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO AS A
JOIN ONLINE_SALE AS B
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC, GENDER ASC;