-- 코드를 입력하세요
-- 입양 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물의 ID와 이름 출력
-- ID 오름차순

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS AS A
LEFT JOIN ANIMAL_INS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.DATETIME IS NULL
ORDER BY A.ANIMAL_ID ASC;