-- 코드를 입력하세요
-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- 회원 이름, 리뷰 텍스트, 리뷰 작성일 출력
SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM MEMBER_PROFILE AS A
JOIN REST_REVIEW AS B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = 
    (SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;